version: "2"

services:
  deployer:
    build: .
    links:
      - hivent
    environment:
      APP_ENV:
      HIVENT_URL: redis://hivent:6379

  hivent:
    image: redis:3.2
    ports:
      - 6379
